### ISSUE TITLE
Failed to activate the atom-image-uploader package

### ISSUE THREAD

**Issue by FilipeNas** [Jiasm/atom-image-uploader#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Ubuntu 19.04
**Thrown From**: [atom-image-uploader](https://github.com/jiasm/atom-image-uploader) package 1.0.11

### Stack Trace

Failed to activate the atom-image-uploader package

```
At Cannot find module 'qiniu'

Error: Cannot find module 'qiniu'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at /packages/atom-image-uploader/lib/getUploader.js:1:170)
    at /packages/atom-image-uploader/lib/getUploader.js:50:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at /packages/atom-image-uploader/lib/atom-image-uploader.js:7:36)
    at /packages/atom-image-uploader/lib/atom-image-uploader.js:95:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:686762)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3428177)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3416311)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.o (/usr/share/atom/resources/app/static/<embedded>:14:1717)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1206583)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1208024)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:348050)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1247210)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1243344)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:283624)
```

### Commands

```
     -0:10.7.0 editor:paste-without-reformatting (input.hidden-input)
  8x -0:08.9.0 core:backspace (input.hidden-input)
  3x -0:07.5.0 core:undo (input.hidden-input)
     -0:03.8.0 atom-image-uploader:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-image-uploader 1.0.11 
Hydrogen 2.9.0 
language-markdown 0.37.0 
markdown-toc 0.4.2 
markdown-writer 2.11.6 
minimap 4.29.9 
teletype 0.13.4 
tool-bar 1.1.11 
tool-bar-markdown-writer 0.5.0 
wombat-dark-syntax 1.2.0 
```

**Comment by Jiasm** [comment]
Looks like a dependent module `qiniu` has not been installed.

Try reinstall `atom-image-uploader`?

**Comment by filipenas** [comment]
npm WARN locking Error: EACCES: permission denied, open '/home/filipe/.atom/.apm/_locks/staging-8b90da951728b929.lock'
npm WARN locking  /home/filipe/.atom/.apm/_locks/staging-8b90da951728b929.lock failed { Error: EACCES: permission denied, open '/home/filipe/.atom/.apm/_locks/staging-8b90da951728b929.lock'
npm WARN locking   stack: 'Error: EACCES: permission denied, open \'/home/filipe/.atom/.apm/_locks/staging-8b90da951728b929.lock\'',
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   syscall: 'open',
npm WARN locking   path: '/home/filipe/.atom/.apm/_locks/staging-8b90da951728b929.lock' }
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-119519-29106-q3ls56.6djmq/package.json'
npm WARN apm-install-dir-119519-29106-q3ls56.6djmq No description
npm WARN apm-install-dir-119519-29106-q3ls56.6djmq No repository field.
npm WARN apm-install-dir-119519-29106-q3ls56.6djmq No README data
npm WARN apm-install-dir-119519-29106-q3ls56.6djmq No license field.

npm ERR! path /home/filipe/.atom/.apm/_locks/staging-8b90da951728b929.lock
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
npm ERR! Error: EACCES: permission denied, open '/home/filipe/.atom/.apm/_locks/staging-8b90da951728b929.lock'
npm ERR!  { Error: EACCES: permission denied, open '/home/filipe/.atom/.apm/_locks/staging-8b90da951728b929.lock'
npm ERR!   stack: 'Error: EACCES: permission denied, open \'/home/filipe/.atom/.apm/_locks/staging-8b90da951728b929.lock\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/home/filipe/.atom/.apm/_locks/staging-8b90da951728b929.lock' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/filipe/.atom/.apm/_logs/2019-06-19T15_17_53_082Z-debug.log

64
atom-image-uploader1.0.11markdown image uploader
Jiasm
Install
178
oss-uploader0.9.0aliyun oss uploader plugin for markdown-assistant
airclear
Install
16
monash-uploader0.2.0Assignment Uploader for some Monash Units
MonashUni-ENG1003
Install
3,501
qiniu-uploader0.0.5qiniu uploader plugin for markdown-assistant
knightli
Install
60
weibo-uploader0.1.8Weibo upload plugin for markdown-assistant
koalli
Install
100
qcloud-uploader0.1.7qcloud uploader plugin for markdown-assistant
tychenjiajun
Install
511
s3uploader1.1.0Files uploader to Amazon S3 by drag & drop
tearoom6
Install
2,718
atom-image-resize0.3.0A resize tool for image files and Base64 encoded images.
geekduck
Install
188
atom-image-paste1.2.0Pastes images from your clipboard into atom. Supports various filetypes and custom image directories.
rustielin
Install
861
atom-hot-package-loader0.5.1Hot reloading for package development
cakecatz
Install
399
insert-image-to-atom-project0.4.0When you paste an image on the clipboard, the img path is inserted. You can set save destination and wwwroot for each project.
shwld
Install
234
hugo-image0.0.8When paste image to markdown ,this will make a directory name filename and will paste the image as a png file in this image ,then will insert a relative image url
1071496910
Install
406
paste-image-20.5.1Paste image to markdown/html.
netwjx
Install
182
atom-markdown-image-paste0.11.0A simple Atom package to paste images into markdown files
VernL
Install
1,357
image-preview0.4.0Preview images embedded in html, css, sass, scss, less, or markdown files.
iyonaga
Install
961
sftp-upload-on-change0.1.0FTP upload files on change package for Atom
andrecasal
Install
27,054
arduino-upload1.5.1Upload your arduino sketches without using the IDE
Sorunome
Install
111
language-image0.1.2Image colorization in atom
thtliife
Install
220
package-reloader1.0.0Reload atom package for package development
hokaccha
Install
143
atom-imagej-mode0.6.0An Atom package for running and evaluating ImageJ scripts.
kephale
Install
354,393
image-view0.64.0Open images in an editor
atom
SettingsDisable
1,238
latex-image-paste0.5.0When an image is pasted into LaTeX, this package creates a directory including the image and inserts a figure including the image path into the document.
simon123h
Install
125
fake-image-snippets1.1.0Fake image please! snippets for Atom
jessy1092
Install
553
draw-on-image0.4.0Draw on your images and screenshots! (Experimental)
p-
Install
18,018
markdown-image-paste2.5.2Just use 'ctrl+v' paste image into markdown
nmecad
Install
780
image-copipe0.3.1Easy image uploads. Copy and paste image to markdown.
sagaraya
Install
4,644
moonloader1.0.7SA MoonLoader extension for Atom
MoonLoader
Install
Featured Packages
1,071,614
Hydrogen2.9.0Run code interactively, inspect data, and plot. All the power of Jupyter kernels, inside your favorite text editor.
nteract
SettingsUninstallDisable
587,702
atom-clock0.1.16Display a customizable clock in the status bar.
b3by
Install
94,791
hey-pane1.1.2Atom Plugin to enlarge the active pane, either with a shortcut or with a super handy follow mode. Inspired by Origami for Sublime Text.
timomeh
Install
55,667
scroll-through-time0.3.1Two fingers scroll moves through time instead of space
mathieudutour
Install
780,553
teletype0.13.4Share your workspace with team members and collaborate on code in real time
atom
SettingsUninstallDisable
74,609
zentabs0.8.9Keep the opened tabs amount below specified limit
ArnaudRinquin
Install
1,043,730
atom-material-syntax1.0.8A dark syntax theme for Atom that uses Google's Material Design color palette
silvestreh
Install
1,675,080
atom-material-ui2.1.3A dynamic UI theme for Atom that follows Google's Material Design Guidelines
atom-material
Install

**Comment by FilipeNas** [comment]
now i have the package installed, but cant do the thing its suppose do to.. tomorrow i will look for any mistakes and let u know
